export type BlipColourSwatch = { id: number; name: string; hex: string };

export const BLIP_COLOUR_SWATCHES: BlipColourSwatch[] = [
	{ id: 0, name: "White", hex: "#fefefe" },
	{ id: 1, name: "Red", hex: "#e03232" },
	{ id: 2, name: "Green", hex: "#71cb71" },
	{ id: 3, name: "Blue", hex: "#5db6e5" },
	{ id: 4, name: "White", hex: "#fefefe" },
	{ id: 5, name: "Yellow", hex: "#eec64e" },
	{ id: 6, name: "Light Red", hex: "#c25050" },
	{ id: 7, name: "Violet", hex: "#9c6eaf" },
	{ id: 8, name: "Pink", hex: "#fe7ac3" },
	{ id: 9, name: "Light Orange", hex: "#f59d79" },
	{ id: 10, name: "Light Brown", hex: "#b18f83" },
	{ id: 11, name: "Light Green", hex: "#8dcea7" },
	{ id: 12, name: "Light Blue", hex: "#70a8ae" },
	{ id: 13, name: "Light Purple", hex: "#d3d1e7" },
	{ id: 14, name: "Dark Purple", hex: "#8f7e98" },
	{ id: 15, name: "Cyan", hex: "#6ac4bf" },
	{ id: 16, name: "Light Yellow", hex: "#d5c398" },
	{ id: 17, name: "Orange", hex: "#ea8e50" },
	{ id: 18, name: "Light Blue", hex: "#97cae9" },
	{ id: 19, name: "Dark Pink", hex: "#b26287" },
	{ id: 20, name: "Dark Yellow", hex: "#8f8d79" },
	{ id: 21, name: "Dark Orange", hex: "#a6755e" },
	{ id: 22, name: "Light Gray", hex: "#afa8a8" },
	{ id: 23, name: "Light Pink", hex: "#e78d9a" },
	{ id: 24, name: "Lemon Green", hex: "#bbd65b" },
	{ id: 25, name: "Forest Green", hex: "#0c7b56" },
	{ id: 26, name: "Electric Blue", hex: "#7ac3fe" },
	{ id: 27, name: "Bright Purple", hex: "#ab3ce6" },
	{ id: 28, name: "Dark Yellow", hex: "#cda80c" },
	{ id: 29, name: "Dark Blue", hex: "#4561ab" },
	{ id: 30, name: "Dark Cyan", hex: "#29a5b8" },
	{ id: 31, name: "Light Brown", hex: "#b89b7b" },
	{ id: 32, name: "Light Blue", hex: "#c8e0fe" },
	{ id: 33, name: "Light Yellow", hex: "#f0f096" },
	{ id: 34, name: "Light Pink", hex: "#ed8ca1" },
	{ id: 35, name: "Light Red", hex: "#f98a8a" },
	{ id: 36, name: "Beige", hex: "#fbeea5" },
	{ id: 37, name: "White", hex: "#fefefe" },
	{ id: 38, name: "Blue", hex: "#2c6db8" },
	{ id: 39, name: "Light Gray", hex: "#9a9a9a" },
	{ id: 40, name: "Dark Gray", hex: "#4c4c4c" },
	{ id: 41, name: "Pink Red", hex: "#f29d9d" },
	{ id: 42, name: "Blue", hex: "#6cb7d6" },
	{ id: 43, name: "Light Green", hex: "#afedae" },
	{ id: 44, name: "Light Orange", hex: "#ffa75f" },
	{ id: 45, name: "White", hex: "#fefefe" },
	{ id: 46, name: "Gold", hex: "#ecf029" },
	{ id: 47, name: "Orange", hex: "#ff9a18" },
	{ id: 48, name: "Brilliant Rose", hex: "#f644a5" },
	{ id: 49, name: "Red", hex: "#e03232" },
	{ id: 50, name: "Medium Purple", hex: "#8a6de3" },
	{ id: 51, name: "Salmon", hex: "#ff8b5c" },
	{ id: 52, name: "Dark Green", hex: "#3a6479" },
	{ id: 53, name: "Blizzard Blue", hex: "#b3ddf3" },
	{ id: 54, name: "Oracle Blue", hex: "#3a6479" },
	{ id: 55, name: "Silver", hex: "#c0c0c0" },
	{ id: 56, name: "Brown", hex: "#847232" },
	{ id: 57, name: "Blue", hex: "#65b9e7" },
	{ id: 58, name: "East Bay", hex: "#4b4175" },
	{ id: 59, name: "Red", hex: "#e03232" },
	{ id: 60, name: "Yellow Orange", hex: "#f0cb58" },
	{ id: 61, name: "Mulberry Pink", hex: "#cd6d9b" },
	{ id: 62, name: "Alto Gray", hex: "#d1d1d1" },
	{ id: 63, name: "Jelly Bean Blue", hex: "#3b7ab0" },
	{ id: 64, name: "Dark Orange", hex: "#b85a17" },
	{ id: 65, name: "Mamba", hex: "#6b5b95" },
	{ id: 66, name: "Yellow Orange", hex: "#f0cb57" },
	{ id: 67, name: "Blue", hex: "#65b9e7" },
	{ id: 68, name: "Blue", hex: "#65b9e7" },
	{ id: 69, name: "Green", hex: "#79cd79" },
	{ id: 70, name: "Yellow Orange", hex: "#efca57" },
	{ id: 71, name: "Yellow Orange", hex: "#efca57" },
	{ id: 72, name: "Transparent Black", hex: "#2a2a2a" },
	{ id: 73, name: "Yellow Orange", hex: "#efca57" },
	{ id: 74, name: "Blue", hex: "#65b9e7" },
	{ id: 75, name: "Red", hex: "#e03232" },
	{ id: 76, name: "Deep Red", hex: "#782323" },
	{ id: 77, name: "Blue", hex: "#65b9e7" },
	{ id: 78, name: "Oracle Blue", hex: "#3a6479" },
	{ id: 79, name: "Transparent Red", hex: "#e03232" },
	{ id: 80, name: "Transparent Blue", hex: "#65b9e7" },
	{ id: 81, name: "Orange", hex: "#f2a400" },
	{ id: 82, name: "Light Green", hex: "#8dcea7" },
	{ id: 83, name: "Purple", hex: "#9c6eaf" },
	{ id: 84, name: "Blue", hex: "#65b9e7" },
	{ id: 85, name: "Transparent Black", hex: "#2a2a2a" },
];

export function blipColourHex(id: number): string {
	return BLIP_COLOUR_SWATCHES.find((swatch) => swatch.id === id)?.hex ?? "#5db6e5";
}
