/* eslint-disable */
/* prettier-ignore */
/* oxlint-disable */
/* oxfmt-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const BLIP_COLOUR_SWATCHES: typeof import('./src/utils/blipColours').BLIP_COLOUR_SWATCHES
  const EXP_LANG_DISMISS_KEY: typeof import('./src/composables/usePreferences').EXP_LANG_DISMISS_KEY
  const EffectScope: typeof import('vue').EffectScope
  const _t: typeof import('./src/composables/useLocale')._t
  const acceptHMRUpdate: typeof import('pinia').acceptHMRUpdate
  const applyLtBatch: typeof import('@laot/nuix').applyLtBatch
  const assetURL: typeof import('./src/utils/assetURL').assetURL
  const blipColourHex: typeof import('./src/utils/blipColours').blipColourHex
  const blipMetas: typeof import('./src/utils/blips').blipMetas
  const blipSpriteId: typeof import('./src/utils/blips').blipSpriteId
  const blipSrc: typeof import('./src/utils/blips').blipSrc
  const buildBlipPayload: typeof import('./src/utils/blipPayload').buildBlipPayload
  const buildGlobalBlipPayload: typeof import('./src/utils/blipPayload').buildGlobalBlipPayload
  const clearNuiMocks: typeof import('@laot/nuix').clearNuiMocks
  const computed: typeof import('vue').computed
  const createApp: typeof import('vue').createApp
  const createPinia: typeof import('pinia').createPinia
  const customRef: typeof import('vue').customRef
  const defineAsyncComponent: typeof import('vue').defineAsyncComponent
  const defineComponent: typeof import('vue').defineComponent
  const defineStore: typeof import('pinia').defineStore
  const effectScope: typeof import('vue').effectScope
  const fetchNui: typeof import('@laot/nuix').fetchNui
  const getActivePinia: typeof import('pinia').getActivePinia
  const getCurrentInstance: typeof import('vue').getCurrentInstance
  const getCurrentScope: typeof import('vue').getCurrentScope
  const getCurrentWatcher: typeof import('vue').getCurrentWatcher
  const h: typeof import('vue').h
  const hexToHsv: typeof import('./src/utils/color').hexToHsv
  const hsvToHex: typeof import('./src/utils/color').hsvToHex
  const iS: typeof import('./src/composables/useScaler').iS
  const inject: typeof import('vue').inject
  const isEnvBrowser: typeof import('@laot/nuix').isEnvBrowser
  const isProxy: typeof import('vue').isProxy
  const isReactive: typeof import('vue').isReactive
  const isReadonly: typeof import('vue').isReadonly
  const isRef: typeof import('vue').isRef
  const isShallow: typeof import('vue').isShallow
  const localeTag: typeof import('./src/composables/useLocale').localeTag
  const mapActions: typeof import('pinia').mapActions
  const mapGetters: typeof import('pinia').mapGetters
  const mapState: typeof import('pinia').mapState
  const mapStores: typeof import('pinia').mapStores
  const mapWritableState: typeof import('pinia').mapWritableState
  const markRaw: typeof import('vue').markRaw
  const nextTick: typeof import('vue').nextTick
  const onActivated: typeof import('vue').onActivated
  const onBeforeMount: typeof import('vue').onBeforeMount
  const onBeforeUnmount: typeof import('vue').onBeforeUnmount
  const onBeforeUpdate: typeof import('vue').onBeforeUpdate
  const onDeactivated: typeof import('vue').onDeactivated
  const onErrorCaptured: typeof import('vue').onErrorCaptured
  const onMounted: typeof import('vue').onMounted
  const onNuiAction: typeof import('@laot/nuix').onNuiAction
  const onNuiMessage: typeof import('@laot/nuix').onNuiMessage
  const onRenderTracked: typeof import('vue').onRenderTracked
  const onRenderTriggered: typeof import('vue').onRenderTriggered
  const onScopeDispose: typeof import('vue').onScopeDispose
  const onServerPrefetch: typeof import('vue').onServerPrefetch
  const onUnmounted: typeof import('vue').onUnmounted
  const onUpdated: typeof import('vue').onUpdated
  const onWatcherCleanup: typeof import('vue').onWatcherCleanup
  const pointColour: typeof import('./src/utils/blips').pointColour
  const pointLabel: typeof import('./src/utils/blips').pointLabel
  const provide: typeof import('vue').provide
  const reactive: typeof import('vue').reactive
  const readableInk: typeof import('./src/utils/color').readableInk
  const readonly: typeof import('vue').readonly
  const ref: typeof import('vue').ref
  const relativeLuminance: typeof import('./src/utils/color').relativeLuminance
  const replaceLtState: typeof import('@laot/nuix').replaceLtState
  const resolveComponent: typeof import('vue').resolveComponent
  const setActivePinia: typeof import('pinia').setActivePinia
  const setMapStoreSuffix: typeof import('pinia').setMapStoreSuffix
  const setNuiMocks: typeof import('@laot/nuix').setNuiMocks
  const shallowReactive: typeof import('vue').shallowReactive
  const shallowReadonly: typeof import('vue').shallowReadonly
  const shallowRef: typeof import('vue').shallowRef
  const sharedLabel: typeof import('./src/composables/useExperimental').sharedLabel
  const spriteTitle: typeof import('./src/utils/blips').spriteTitle
  const storeToRefs: typeof import('pinia').storeToRefs
  const toRaw: typeof import('vue').toRaw
  const toRef: typeof import('vue').toRef
  const toRefs: typeof import('vue').toRefs
  const toValue: typeof import('vue').toValue
  const triggerRef: typeof import('vue').triggerRef
  const uiScaleFactor: typeof import('./src/composables/useScaler').uiScaleFactor
  const unref: typeof import('vue').unref
  const useAttrs: typeof import('vue').useAttrs
  const useCssModule: typeof import('vue').useCssModule
  const useCssVars: typeof import('vue').useCssVars
  const useExperimental: typeof import('./src/composables/useExperimental').useExperimental
  const useId: typeof import('vue').useId
  const useLegendStore: typeof import('./src/stores/legend').useLegendStore
  const useLocaleStore: typeof import('./src/stores/locale').useLocaleStore
  const useMainStore: typeof import('./src/stores/main').useMainStore
  const useMapBlipFocus: typeof import('./src/composables/useMapBlipFocus').useMapBlipFocus
  const useMarkersStore: typeof import('./src/stores/markers').useMarkersStore
  const useModel: typeof import('vue').useModel
  const usePreferences: typeof import('./src/composables/usePreferences').usePreferences
  const useScaler: typeof import('./src/composables/useScaler').useScaler
  const useSettingsCache: typeof import('./src/composables/useSettingsCache').useSettingsCache
  const useSettingsNavigation: typeof import('./src/composables/useSettingsNavigation').useSettingsNavigation
  const useSettingsStore: typeof import('./src/stores/settings').useSettingsStore
  const useSlots: typeof import('vue').useSlots
  const useStats: typeof import('./src/composables/useStats').useStats
  const useStorage: typeof import('@vueuse/core').useStorage
  const useTemplateRef: typeof import('vue').useTemplateRef
  const watch: typeof import('vue').watch
  const watchEffect: typeof import('vue').watchEffect
  const watchPostEffect: typeof import('vue').watchPostEffect
  const watchSyncEffect: typeof import('vue').watchSyncEffect
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, Slot, Slots, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, ShallowRef, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { Preferences } from './src/composables/usePreferences'
  import('./src/composables/usePreferences')
  // @ts-ignore
  export type { BlipColourSwatch } from './src/utils/blipColours'
  import('./src/utils/blipColours')
  // @ts-ignore
  export type { BlipDraft, GlobalBlipDraft } from './src/utils/blipPayload'
  import('./src/utils/blipPayload')
  // @ts-ignore
  export type { BlipMeta } from './src/utils/blips'
  import('./src/utils/blips')
  // @ts-ignore
  export type { Hsv } from './src/utils/color'
  import('./src/utils/color')
  // @ts-ignore
  export type { Page, StatSkillId, StatSkill, StatCareer, StatsPayload, LocaleStore, MapInfoState, SettingsCategory, SettingKind, GameSettingRow, KeyBindingGroup, KeyBindingRow, SettingsRow, SettingsState, GtaAlertButton, GtaAlertState, SettingsStore, MainStore, Player, MarkerGroup, MarkerShare, MarkerPoint, MarkerRequest, MarkerDraft, GlobalCategory, MarkerSheet, MarkerNoticeKind, MarkersStore, LegendKind, LegendRow, LegendGroup, LegendToast, LegendStatus, LegendState, LegendStore } from './src/types/index'
  import('./src/types/index')
}

// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface GlobalComponents {}
  interface ComponentCustomProperties {
    readonly BLIP_COLOUR_SWATCHES: UnwrapRef<typeof import('./src/utils/blipColours')['BLIP_COLOUR_SWATCHES']>
    readonly EXP_LANG_DISMISS_KEY: UnwrapRef<typeof import('./src/composables/usePreferences')['EXP_LANG_DISMISS_KEY']>
    readonly EffectScope: UnwrapRef<typeof import('vue')['EffectScope']>
    readonly _t: UnwrapRef<typeof import('./src/composables/useLocale')['_t']>
    readonly acceptHMRUpdate: UnwrapRef<typeof import('pinia')['acceptHMRUpdate']>
    readonly applyLtBatch: UnwrapRef<typeof import('@laot/nuix')['applyLtBatch']>
    readonly assetURL: UnwrapRef<typeof import('./src/utils/assetURL')['assetURL']>
    readonly blipColourHex: UnwrapRef<typeof import('./src/utils/blipColours')['blipColourHex']>
    readonly blipMetas: UnwrapRef<typeof import('./src/utils/blips')['blipMetas']>
    readonly blipSpriteId: UnwrapRef<typeof import('./src/utils/blips')['blipSpriteId']>
    readonly blipSrc: UnwrapRef<typeof import('./src/utils/blips')['blipSrc']>
    readonly buildBlipPayload: UnwrapRef<typeof import('./src/utils/blipPayload')['buildBlipPayload']>
    readonly buildGlobalBlipPayload: UnwrapRef<typeof import('./src/utils/blipPayload')['buildGlobalBlipPayload']>
    readonly clearNuiMocks: UnwrapRef<typeof import('@laot/nuix')['clearNuiMocks']>
    readonly computed: UnwrapRef<typeof import('vue')['computed']>
    readonly createApp: UnwrapRef<typeof import('vue')['createApp']>
    readonly createPinia: UnwrapRef<typeof import('pinia')['createPinia']>
    readonly customRef: UnwrapRef<typeof import('vue')['customRef']>
    readonly defineAsyncComponent: UnwrapRef<typeof import('vue')['defineAsyncComponent']>
    readonly defineComponent: UnwrapRef<typeof import('vue')['defineComponent']>
    readonly defineStore: UnwrapRef<typeof import('pinia')['defineStore']>
    readonly effectScope: UnwrapRef<typeof import('vue')['effectScope']>
    readonly fetchNui: UnwrapRef<typeof import('@laot/nuix')['fetchNui']>
    readonly getActivePinia: UnwrapRef<typeof import('pinia')['getActivePinia']>
    readonly getCurrentInstance: UnwrapRef<typeof import('vue')['getCurrentInstance']>
    readonly getCurrentScope: UnwrapRef<typeof import('vue')['getCurrentScope']>
    readonly getCurrentWatcher: UnwrapRef<typeof import('vue')['getCurrentWatcher']>
    readonly h: UnwrapRef<typeof import('vue')['h']>
    readonly hexToHsv: UnwrapRef<typeof import('./src/utils/color')['hexToHsv']>
    readonly hsvToHex: UnwrapRef<typeof import('./src/utils/color')['hsvToHex']>
    readonly iS: UnwrapRef<typeof import('./src/composables/useScaler')['iS']>
    readonly inject: UnwrapRef<typeof import('vue')['inject']>
    readonly isEnvBrowser: UnwrapRef<typeof import('@laot/nuix')['isEnvBrowser']>
    readonly isProxy: UnwrapRef<typeof import('vue')['isProxy']>
    readonly isReactive: UnwrapRef<typeof import('vue')['isReactive']>
    readonly isReadonly: UnwrapRef<typeof import('vue')['isReadonly']>
    readonly isRef: UnwrapRef<typeof import('vue')['isRef']>
    readonly isShallow: UnwrapRef<typeof import('vue')['isShallow']>
    readonly localeTag: UnwrapRef<typeof import('./src/composables/useLocale')['localeTag']>
    readonly mapActions: UnwrapRef<typeof import('pinia')['mapActions']>
    readonly mapGetters: UnwrapRef<typeof import('pinia')['mapGetters']>
    readonly mapState: UnwrapRef<typeof import('pinia')['mapState']>
    readonly mapStores: UnwrapRef<typeof import('pinia')['mapStores']>
    readonly mapWritableState: UnwrapRef<typeof import('pinia')['mapWritableState']>
    readonly markRaw: UnwrapRef<typeof import('vue')['markRaw']>
    readonly nextTick: UnwrapRef<typeof import('vue')['nextTick']>
    readonly onActivated: UnwrapRef<typeof import('vue')['onActivated']>
    readonly onBeforeMount: UnwrapRef<typeof import('vue')['onBeforeMount']>
    readonly onBeforeUnmount: UnwrapRef<typeof import('vue')['onBeforeUnmount']>
    readonly onBeforeUpdate: UnwrapRef<typeof import('vue')['onBeforeUpdate']>
    readonly onDeactivated: UnwrapRef<typeof import('vue')['onDeactivated']>
    readonly onErrorCaptured: UnwrapRef<typeof import('vue')['onErrorCaptured']>
    readonly onMounted: UnwrapRef<typeof import('vue')['onMounted']>
    readonly onNuiAction: UnwrapRef<typeof import('@laot/nuix')['onNuiAction']>
    readonly onNuiMessage: UnwrapRef<typeof import('@laot/nuix')['onNuiMessage']>
    readonly onRenderTracked: UnwrapRef<typeof import('vue')['onRenderTracked']>
    readonly onRenderTriggered: UnwrapRef<typeof import('vue')['onRenderTriggered']>
    readonly onScopeDispose: UnwrapRef<typeof import('vue')['onScopeDispose']>
    readonly onServerPrefetch: UnwrapRef<typeof import('vue')['onServerPrefetch']>
    readonly onUnmounted: UnwrapRef<typeof import('vue')['onUnmounted']>
    readonly onUpdated: UnwrapRef<typeof import('vue')['onUpdated']>
    readonly onWatcherCleanup: UnwrapRef<typeof import('vue')['onWatcherCleanup']>
    readonly pointColour: UnwrapRef<typeof import('./src/utils/blips')['pointColour']>
    readonly pointLabel: UnwrapRef<typeof import('./src/utils/blips')['pointLabel']>
    readonly provide: UnwrapRef<typeof import('vue')['provide']>
    readonly reactive: UnwrapRef<typeof import('vue')['reactive']>
    readonly readableInk: UnwrapRef<typeof import('./src/utils/color')['readableInk']>
    readonly readonly: UnwrapRef<typeof import('vue')['readonly']>
    readonly ref: UnwrapRef<typeof import('vue')['ref']>
    readonly relativeLuminance: UnwrapRef<typeof import('./src/utils/color')['relativeLuminance']>
    readonly replaceLtState: UnwrapRef<typeof import('@laot/nuix')['replaceLtState']>
    readonly resolveComponent: UnwrapRef<typeof import('vue')['resolveComponent']>
    readonly setActivePinia: UnwrapRef<typeof import('pinia')['setActivePinia']>
    readonly setMapStoreSuffix: UnwrapRef<typeof import('pinia')['setMapStoreSuffix']>
    readonly setNuiMocks: UnwrapRef<typeof import('@laot/nuix')['setNuiMocks']>
    readonly shallowReactive: UnwrapRef<typeof import('vue')['shallowReactive']>
    readonly shallowReadonly: UnwrapRef<typeof import('vue')['shallowReadonly']>
    readonly shallowRef: UnwrapRef<typeof import('vue')['shallowRef']>
    readonly storeToRefs: UnwrapRef<typeof import('pinia')['storeToRefs']>
    readonly toRaw: UnwrapRef<typeof import('vue')['toRaw']>
    readonly toRef: UnwrapRef<typeof import('vue')['toRef']>
    readonly toRefs: UnwrapRef<typeof import('vue')['toRefs']>
    readonly toValue: UnwrapRef<typeof import('vue')['toValue']>
    readonly triggerRef: UnwrapRef<typeof import('vue')['triggerRef']>
    readonly uiScaleFactor: UnwrapRef<typeof import('./src/composables/useScaler')['uiScaleFactor']>
    readonly unref: UnwrapRef<typeof import('vue')['unref']>
    readonly useAttrs: UnwrapRef<typeof import('vue')['useAttrs']>
    readonly useCssModule: UnwrapRef<typeof import('vue')['useCssModule']>
    readonly useCssVars: UnwrapRef<typeof import('vue')['useCssVars']>
    readonly useExperimental: UnwrapRef<typeof import('./src/composables/useExperimental')['useExperimental']>
    readonly useId: UnwrapRef<typeof import('vue')['useId']>
    readonly useLegendStore: UnwrapRef<typeof import('./src/stores/legend')['useLegendStore']>
    readonly useLocaleStore: UnwrapRef<typeof import('./src/stores/locale')['useLocaleStore']>
    readonly useMainStore: UnwrapRef<typeof import('./src/stores/main')['useMainStore']>
    readonly useMarkersStore: UnwrapRef<typeof import('./src/stores/markers')['useMarkersStore']>
    readonly useModel: UnwrapRef<typeof import('vue')['useModel']>
    readonly usePreferences: UnwrapRef<typeof import('./src/composables/usePreferences')['usePreferences']>
    readonly useScaler: UnwrapRef<typeof import('./src/composables/useScaler')['useScaler']>
    readonly useSettingsCache: UnwrapRef<typeof import('./src/composables/useSettingsCache')['useSettingsCache']>
    readonly useSettingsNavigation: UnwrapRef<typeof import('./src/composables/useSettingsNavigation')['useSettingsNavigation']>
    readonly useSettingsStore: UnwrapRef<typeof import('./src/stores/settings')['useSettingsStore']>
    readonly useSlots: UnwrapRef<typeof import('vue')['useSlots']>
    readonly useStats: UnwrapRef<typeof import('./src/composables/useStats')['useStats']>
    readonly useStorage: UnwrapRef<typeof import('@vueuse/core')['useStorage']>
    readonly useTemplateRef: UnwrapRef<typeof import('vue')['useTemplateRef']>
    readonly watch: UnwrapRef<typeof import('vue')['watch']>
    readonly watchEffect: UnwrapRef<typeof import('vue')['watchEffect']>
    readonly watchPostEffect: UnwrapRef<typeof import('vue')['watchPostEffect']>
    readonly watchSyncEffect: UnwrapRef<typeof import('vue')['watchSyncEffect']>
  }
}