/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BlipColourId: typeof import('./src/pages/Map3d/components/BlipColourId.vue')['default']
    BlipIcon: typeof import('./src/components/BlipIcon.vue')['default']
    BlipPicker: typeof import('./src/pages/Map3d/components/BlipPicker.vue')['default']
    BrandLogo: typeof import('./src/components/BrandLogo.vue')['default']
    GtaAlertModal: typeof import('./src/components/GtaAlertModal.vue')['default']
    GtaMap: typeof import('./src/pages/GtaMap/GtaMap.vue')['default']
    Map3d: typeof import('./src/pages/Map3d/Map3d.vue')['default']
    MapBlipPanel: typeof import('./src/pages/Map3d/components/MapBlipPanel.vue')['default']
    MapBlipShareDialog: typeof import('./src/pages/Map3d/components/MapBlipShareDialog.vue')['default']
    MapControls: typeof import('./src/pages/Map3d/components/MapControls.vue')['default']
    MapInfo: typeof import('./src/pages/Map3d/components/MapInfo.vue')['default']
    MapMarkers: typeof import('./src/pages/Map3d/components/MapMarkers.vue')['default']
    MapSearchInput: typeof import('./src/pages/Map3d/components/MapSearchInput.vue')['default']
    PauseHome: typeof import('./src/pages/Pause/PauseHome.vue')['default']
    Preferences: typeof import('./src/pages/Settings/Preferences.vue')['default']
    Settings: typeof import('./src/pages/Settings/Settings.vue')['default']
    Stats: typeof import('./src/pages/Stats/Stats.vue')['default']
  }
}
